ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- kubernetes
- " lxc "
- podman

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- sudo
- containerd
- kubernetes
- lxc
- container
- argo
- s3 
- wazuh
- wordpress
- gitlab
- cognito
- istio
- terraform
- aws
- opensearch
- kibana
- knock
- google
- slack
- notion

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample

